server:
  port: 8080

mqtt:
  uris:
    - tcp://localhost:1883
#  username: user
#  password: password
  client-id: my-example-app-client
  default-publish-topic: app/events/default
  subscription-topics:
    - app/commands/#
    - system/notifications
  subscription-qos:
    - 1
    - 2

